### ISSUE TITLE
Show title isnt searched correctly in find torrent.

### ISSUE THREAD

**Issue by rocksamson** [DuckieTV/duckietv-builder#8]
An example is the following;

S.W.A.T. 2017 is entered in my favorites. it appears in the calendar as S.W.A.T S03E02 correctly but is never downloaded automatically because "find torrent" is omitting the "." between each letters thus never being found and downloaded. If you do a manual search "find show" you clearly see: "SWAT S03E02" without any "." when manually altered to S.W.A.T. all titles are found and can be manually selected. There is no field allowing us to manually change what is searched for the selected favorites or if you provide us with the location of the name of the log file used to store the favorites we might be able to manually alter the name/correct the error?

**Comment by garfield69** [comment]
You did not specify which version or flavour of Dtv you are using, but I am going to guess you are on Dtv 1.1.5 because that version has this problem.

if you upgrade to using the latest Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases you will find that s.w.a.t is searched correctly with the full stops in the title.
![image](https://user-images.githubusercontent.com/6933240/67626340-64bedb80-f8a6-11e9-82cc-824bac61dfe8.png)

**Comment by rocksamson** [comment]
Thank you!

Rock
